spring:
  application:
    name: hhplus-lecture
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lecture?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
  sql:
    init:
      schema-locations: classpath*:sql/schema.sql
      mode: always