CREATE DATABASE IF NOT EXISTS `lecture`;

DROP TABLE IF EXISTS enrollment;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS lesson;

CREATE TABLE IF NOT EXISTS `user` (
  id BIGINT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS lesson (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    maximum BIGINT NOT NULL,
    enroll_count BIGINT NOT NULL,
    due_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS enrollment (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    lesson_id BIGINT NOT NULL,
    is_attended BOOLEAN NOT NULL,
    FOREIGN KEY (user_id) REFERENCES `user`(id),
    FOREIGN KEY (lesson_id) REFERENCES lesson(id)
);

INSERT INTO user VALUES (1);
INSERT INTO user VALUES (2);
INSERT INTO user VALUES (3);
INSERT INTO user VALUES (4);
INSERT INTO user VALUES (5);
INSERT INTO user VALUES (6);
INSERT INTO user VALUES (7);
INSERT INTO user VALUES (8);
INSERT INTO user VALUES (9);
INSERT INTO user VALUES (10);
INSERT INTO user VALUES (11);
INSERT INTO user VALUES (12);
INSERT INTO user VALUES (13);
INSERT INTO user VALUES (14);
INSERT INTO user VALUES (15);
INSERT INTO user VALUES (16);
INSERT INTO user VALUES (17);
INSERT INTO user VALUES (18);
INSERT INTO user VALUES (19);
INSERT INTO user VALUES (20);
INSERT INTO user VALUES (21);
INSERT INTO user VALUES (22);
INSERT INTO user VALUES (23);
INSERT INTO user VALUES (24);
INSERT INTO user VALUES (25);
INSERT INTO user VALUES (26);
INSERT INTO user VALUES (27);
INSERT INTO user VALUES (28);
INSERT INTO user VALUES (29);
INSERT INTO user VALUES (30);
INSERT INTO user VALUES (31);

INSERT INTO lesson (maximum, enroll_count, due_date) VALUES (30, 0, '2024-04-20');

